### ISSUE TITLE
Duplication bug found when used with Tetra

### ISSUE THREAD

**Issue by Mekelaina** [jeremiahwinsley/InvTweaksRenewed#10]
Hello. I am building a private pack and during testing found that when in the interface of a tetra workbench and one clicks the sort button, with more than one stack/item in their inventory. it causes a full copy of al items not in the tetra bench to be spat out of the bench. this works in survival and creative. This is in 1.20.1 so this may have been patched already, but I figured i should make you aware of this regardless. 

[here's](https://youtu.be/JlgF-JnJEIo) a video of me doing the bug

**Comment by JaisDK** [comment]
I don't know what's going on there but you should probably blacklist that screen from having sorting. There was something fixed in 1.21 regarding hidden slots which might be what's going on here.

**Comment by Mekelaina** [comment]
> I don't know what's going on there but you should probably blacklist that screen from having sorting. There was something fixed in 1.21 regarding hidden slots which might be what's going on here.

maybe. I was unaware you could blacklist inventories from being sortable. I will try that out.
