### ISSUE TITLE
Update to latest Neoforge and release new version for 1.20.4

### ISSUE THREAD

**Issue by vrozkovec** [jeremiahwinsley/InvTweaksRenewed#2]
Hi, as NeoForge is in stable since 20.4.167: https://maven.neoforged.net/releases/net/neoforged/neoforge/20.4.227/neoforge-20.4.227-changelog.txt
would it be, please, possible to catch-up with changes in NeoForge and release new version for 1.20.4?

**Comment by JaisDK** [comment]
skipping 1.20.4 and going to 1.20.6
