### ISSUE TITLE
Sorting the inventories of machines from the Thermal Series removes all the RF

### ISSUE THREAD

**Issue by vizthex123** [jeremiahwinsley/InvTweaksRenewed#3]
I already told the TE devs about this,a nd King Lemming said he didn't have a solution - so I figured I'd post here.

If machines have any augments in them and you sort the inventory, it sorts the augments and causes TE to register a change in the augment list, which removes the RF stored in said machines.

If you could have the mod blacklist all TE machine UIs by default it'd be nice (and hopefully it works lol).

Here's my game log if ya need it:
[latest.log](https://github.com/JDKDigital/InvTweaksRefoxed/files/15367460/latest.log)

**Comment by JaisDK** [comment]
I'll add them, for now you can add this to the config

[[sorting.containerOverrides]]
		containerClass = "cofh.thermal.core.client.gui.*"
		sortRange = ""

**Comment by vizthex123** [comment]
Noice, thanks.
