### ISSUE TITLE
Cannot connect to vanilla minecraft server

### ISSUE THREAD

**Issue by elizabethlfransen** [jeremiahwinsley/InvTweaksRenewed#4]
# Problem
Cannot connect to a vanilla minecraft server.
I get message `Client disconnected with reason: You are trying to connect to a server that is not running NeoForge, but you have mods that require it. A connection could not be established.`

#  Version
Client - 1.20.6
Server - 1.20.6 Vanilla
NeoForge - 20.6.100-beta
InvTweaksRefoxed - 1.20.6-1.1.1

**Comment by JaisDK** [comment]
is your server running NeoForge?

**Comment by elizabethlfransen** [comment]
> is your server running NeoForge?

No I've updated the issue to reflect this

**Comment by JaisDK** [comment]
is the mod supposed to work with vanilla servers?

**Comment by elizabethlfransen** [comment]
The mod page says "This mod allows you to easily manage your inventory, in both single player and multiplayer". And the original mod worked as client-side only mod. So i'm making the assumption that, that is the case.

I could be wrong about this, but that is my understanding of the mod.

**Comment by JaisDK** [comment]
I asked around, it did indeed used to work with vanilla servers so I'll look into getting that functionality back.
