### ISSUE TITLE
Sorting in LaserIO gui causes entire inventory to get deleted

### ISSUE THREAD

**Issue by Slappy826** [jeremiahwinsley/InvTweaksRenewed#5]
https://streamable.com/tcffw9

The only two mods I have installed in the video is LaserIO 1.6.8 and this mod version 1.1.0 on forge 47.2.20, minecraft version 1.20.1

**Comment by Slappy826** [comment]
```
[[sorting.containerOverrides]]
	containerClass = "com.direwolf20.laserio.client.screens.*"
	sortRange = ""
```

i was able to disable the sorting functionality in the laserio guis by adding this to the config

**Comment by Bamberghh** [comment]
Can confirm, with this mod of version 1.1.0 and LaserIO of version 1.6.8.

To reproduce this issue, sort the inventory (press the sorting button in the GUI or middle mouse button) while in the item card GUI and your inventory will get deleted (see the attached videos). Each time you press the sort button, 15 item stacks at most get deleted, like you see in the second video - from a full player inventory 15 stacks get deleted then another 15, then the last 6.

As for why this happens, I can only think of the 15 ghost item slots that the LaserIO filters have - maybe InvTweaks tries to put the items into the ghost slots and deletes them, but again, I'm not sure. Also I've tested this with the [Inventory Sorter](https://www.curseforge.com/minecraft/mc-mods/inventory-sorter) mod but the items in that case aren't sorted and therefore aren't deleted.

https://github.com/user-attachments/assets/9b1f06fc-8c4e-4e64-97c4-b950893bae73

https://github.com/user-attachments/assets/0ad4356a-3841-460b-b01a-f971e5ff95a3

**Comment by Bamberghh** [comment]
This issue is also in the LaserIO GitHub - see [issue 265](https://github.com/Direwolf20-MC/LaserIO/issues/265)

**Comment by pmteixeira07** [comment]
This is a problem with the sorting of this mod, not with other mods. Tested it in All the mods 9: To the sky, and the sorting of this mod (both hotkey and button in inventories) deletes mine and the non-vanilla blocks inventories.
