### ISSUE TITLE
Mod prints the class name of every screen opened to the client log

### ISSUE THREAD

**Issue by James103** [jeremiahwinsley/InvTweaksRenewed#6]
Minecraft 1.20.1
Inventory Tweaks Refoxed 1.1.0
Forge 47.3.0
Mod pack: [Project Architect 2](https://www.curseforge.com/minecraft/modpacks/project-architect-2) version 2.6

Every time an inventory screen is opened, Inventory Tweaks Refoxed prints the name of the class responsible for the inventory screen to the client-side log. For example, the following lines in the log are logged when opening the player's inventory, then a Sophisticated Backpack, and finally a Wireless Crafting Terminal from AE2WTLib.
```
[23:34:21] [Render thread/INFO] [invtweaks/]: net.minecraft.client.gui.screens.inventory.InventoryScreen
[23:39:08] [Render thread/INFO] [invtweaks/]: net.p3pp3rf1y.sophisticatedbackpacks.client.gui.BackpackScreen
[23:39:11] [Render thread/INFO] [invtweaks/]: de.mari_023.ae2wtlib.wct.WCTScreen
```

Where in the code is causing these lines to be logged, and can it be disabled so as to not clog up the logs?

**Comment by JaisDK** [comment]
It's on purpose to help with configuring, but it should have been writing to the debug log not the regular log. I'll get it moved and maybe put a config for it as well.
